// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "fltk2.h"

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(327, 501);
    w = o; if (w) {/* empty */}
    o->color(FL_DARK3);
    o->selection_color((Fl_Color)31);
    o->hotspot(o);
    { Fl_Choice* o = new Fl_Choice(0, 0, 330, 50, "LUNA");
      o->down_box(FL_FLAT_BOX);
      o->color((Fl_Color)239);
      o->selection_color((Fl_Color)231);
      o->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      Fl_Group::current()->resizable(o);
      o->add("MAI");
    } // Fl_Choice* o
    o->set_modal();
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
