// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef gpt_h
#define gpt_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
#endif
