// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "gpt.h"

static void
cb_(Fl_Input* o, void* v)
{
  printf("%s\n", o->value());
  o->parent()->child(2)->color(FL_RED);
}

int
main(int argc, char** argv)
{
  Fl_Double_Window* w;
  {
    Fl_Double_Window* o = new Fl_Double_Window(429, 694);
    w                   = o;
    if (w) { /* empty */
    }
    {
      Fl_Input* o = new Fl_Input(0, 651, 425, 47);
      o->callback((Fl_Callback*) cb_);
    } // Fl_Input* o
    {
      Fl_Output* o = new Fl_Output(-9, 2, 434, 655);
      Fl_Group::current()->resizable(o);
      o->window()->hotspot(o);
    } // Fl_Output* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
